image:
  repository: registry.internal.huggingface.tech/deepsite
  name: deepsite
  tag: 0.0.0-latest
  pullPolicy: IfNotPresent

replicas: 1

domain: deepsite.hf.co

networkPolicy:
  enabled: true
  allowedBlocks: []
  # allowedBlocks:
  #   - 10.0.240.0/24
  #   - 10.0.241.0/24
  #   - 10.0.242.0/24
  #   - 10.0.243.0/24
  #   - 10.0.244.0/24
  #   - 10.240.0.0/24
  #   - 10.16.0.0/16

service:
  type: NodePort
  annotations: { }

serviceAccount:
  enabled: false
  create: false
  name: ""
  automountServiceAccountToken: true
  annotations: { }

ingress:
  enabled: true
  path: "/"
  annotations: { }
  # className: "nginx"
  tls: { }
    # secretName: XXX

ingressInternal:
  enabled: false
  path: "/"
  annotations: { }
  # className: "nginx"
  tls: { }

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
nodeSelector: {}
tolerations: []

envVars: { }

infisical:
  enabled: false
  env: ""
  project: "deepsite-f-hvj"
  url: ""
  resyncInterval: 60
  operatorSecretName: "deepsite-operator-secrets"
  operatorSecretNamespace: "hub-utils"

# Allow to environment injections on top or instead of infisical
extraEnvFrom: []
extraEnv: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: ""
  targetCPUUtilizationPercentage: ""

## Metrics removed; monitoring configuration no longer used
