name: Deploy to k8s
on:
  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: 
      group: cpu-high
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.internal.huggingface.tech
          username: ${{ secrets.DOCKER_INTERNAL_USERNAME }}
          password: ${{ secrets.DOCKER_INTERNAL_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.internal.huggingface.tech/deepsite/deepsite
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,prefix=sha-,format=short,sha-len=8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Build and Publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-to: type=gha,mode=max,scope=amd64
          cache-from: type=gha,scope=amd64
          provenance: false

  deploy:
    name: Deploy on prod
    runs-on: ubuntu-latest
    needs: ["build-and-publish"]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Gen values
        run: |
          VALUES=$(cat <<-END
          image:
            tag: "sha-${{ env.GITHUB_SHA_SHORT }}"
          END
          )
          echo "VALUES=$(echo "$VALUES" | yq -o=json | jq tostring)" >> $GITHUB_ENV

      - name: Deploy on infra-deployments
        uses: the-actions-org/workflow-dispatch@v2
        with:
          workflow: Update application single value
          repo: huggingface/infra-deployments
          wait-for-completion: true
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          ref: refs/heads/main
          token: ${{ secrets.GIT_TOKEN_INFRA_DEPLOYMENT }}
          inputs: '{"path": "hub/deepsite/deepsite.yaml", "value": ${{ env.VALUES }}, "url": "${{ github.event.head_commit.url }}"}'
